[package]
name = "payments_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1"
rust_decimal = { version = "1", features = ["serde-with-str", "macros"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
